version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7

  pre_build:
    commands:
      - echo Test the python application.
      - pip install -r requirements.txt
      - |
        set e 
        if [ "$BUILD_TYPE" = "UNIT_TEST" ]; then 
        flake8 app.py
        pytest
        fi

  build:
    commands:
      - echo Build the CSS using less
      - |
        set e 
        if [ "$BUILD_TYPE" = "BUILD" ]; then 
        npm install -g less
        mkdir -p static/css
        lessc styles.less static/css/styles.css
        fi

artifacts:
  files:
    - '**/*'
  name: python-app-$(date +%y%m%d%H%M).zip
